DAG-546: Disable scrolling for input type Number
navikt/dp-soknadsdialog pull request #107
Opened 2022-10-31 10:01 UTC by nattaphongklinjan

Første forslag som ikke fungerer helt `<input type="text" inputmode="numeric" pattern="[0-9]*">`. Med det får man lov å skrive inn bokstaver, det vil vi kanskje ikke?
Tråd på slack: https://nav-it.slack.com/archives/C7NE7A8UF/p1667203911279829

Dette kodesnuttet bare disable scrolling innen input feltet. Ikke helt sikker på om UU eksterter liker denne løsningen. Men det kan vi ta det opp når vi skal ha neste møte med de.

2022-10-31 10:12 UTC, ssaegrov commented
Vi kan vel tillate at de skriver tekst så lenge vi validerer og gir de feilmelding hvis de skriver noe annet enn tall?
Med type="number" så endrer man også verdien med pil opp/ned, burde vi i så fall disable den eventen også?
Jeg tenker dette er gode spørsmål å stille Morten på torsdag når vi kjører skjermleser test.

2022-10-31 10:14 UTC, nattaphongklinjan commented
> 

Enig, jeg lar det står til når vi fikk snakket med Morten

2022-10-31 11:26 UTC, hanneolsen commented
Gov.co.uk har skrevet om dette, de gikk fra å bruke type number til text på grunn av blant annet issues med scroll, men også issues med NVDA. Jeg tror vi bør gå for en lignende løsning som de: https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

2022-11-02 07:38 UTC, androa commented
Enig med @hanneolsen, gov.uk (og mange flere) har vært i samme båt før, og konklusjonen pleier å bli; bare ikke bruk `type="number"`. `inputmode="numeric"` gjør jo uansett det vi *egentlig* vil, å gi numerisk tastatur på mobil.

2022-11-04 07:33 UTC, androa commented
>Jeg tenker dette er gode spørsmål å stille Morten på torsdag når vi kjører skjermleser test.

Vi glemte vel å spørre om dette 😓

2022-11-04 07:38 UTC, androa requested changes

2022-11-04 07:38 UTC, androa commented on src/components/faktum/FaktumNumber.tsx
> +        onWheel={() => (document.activeElement as HTMLElement).blur()}
```suggestion
```

2022-11-04 07:38 UTC, androa commented on src/components/faktum/FaktumNumber.tsx
>          type="number"
```suggestion
        type="text"
        inputmode="numeric"
        pattern="[0-9]*"
```

2022-11-04 07:38 UTC, androa commented on src/components/faktum/FaktumNumber.tsx
>          step={faktum.type === "double" ? "0.1" : "1"}
```suggestion
```

2022-11-08 14:06 UTC, closed without merging